# Generated by Django 4.1.7 on 2023-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('highlight', models.TextField(max_length=250)),
                ('year', models.IntegerField()),
                ('company', models.CharField(max_length=100)),
                ('img', models.URLField()),
            ],
        ),
    ]
