# Generated by Django 4.1.7 on 2023-04-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_topp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topp',
            name='img',
            field=models.URLField(default='Enter URL', max_length=500),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField(verbose_name='$0.00')),
                ('topp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.topp')),
            ],
        ),
    ]
