# Generated by Django 4.1.7 on 2023-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_topp_img_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
