# Generated by Django 4.1.7 on 2023-04-11 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=25, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
