# Generated by Django 4.1.7 on 2023-04-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
