# Generated by Django 4.1.7 on 2023-04-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='print',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='year',
        ),
        migrations.RemoveField(
            model_name='topp',
            name='company',
        ),
        migrations.AddField(
            model_name='topp',
            name='company',
            field=models.ManyToManyField(to='main_app.company'),
        ),
    ]
